/**
 * WARNING: This file was auto-generated by svgr. Do not edit.
 */
import * as React from 'react';
import type { SVGProps } from 'react';
const SvgRecordCircleIcon = (props: SVGProps<SVGSVGElement>) => (
  <svg
    fill="currentcolor"
    width={16}
    height={16}
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    strokeWidth="1"
  >
    <circle cx="8" cy="8" r="8">
      <animate
        attributeType="XML"
        attributeName="r"
        values="8;6;8"
        dur="2s"
        begin="0.7s"
        repeatCount="indefinite"
      />
    </circle>
  </svg>
);
export default SvgRecordCircleIcon;